[theme]
base = "dark"
backgroundColor = "#0B0B0D"
secondaryBackgroundColor = "#1A1C23"
textColor = "#E4E1EA"
primaryColor = "#B6A5FF"
font = "sans serif"

[server]
headless = true
enableStaticServing = true
